### ISSUE TITLE
Add support of disabling some rows and adding custom component to popup headers, rows, columns

### ISSUE THREAD

**Issue by nkovalenko-sc** [OpusCapita/react-async-select#15]
I'm implementing a feature related to approval limits and I need few things:
- Disable some rows.
- Add some JSX component to headers.
- Customize search field in header.

Issue - https://github.com/OpusCapita/invoice/issues/1822.
Specs - https://github.com/OpusCapita/ipa-specs/issues/123.
Mockups - https://github.com/OpusCapita/ipa-specs/files/2615354/Approval.limits.UI.-.v6.pptx (last two screens).

**Comment by jluukka** [comment]
Closing this issue as done. Follow-up fixes related to this should be included in a separate issue.
